const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const workerSource=fs.readFileSync('src/main/resources/static/smartapartment/js/worker-attendance-module.js','utf8');
function worker({reason='Parts unavailable',response={ok:true,status:204,json:async()=>({})},fetcher}={}){
 const events=[],calls=[],toasts=[],buttons=new Map();for(const id of ['btnWorkerClockIn','btnWorkerClockOut','btnWorkerStartBreak','btnWorkerEndBreak'])buttons.set(id,{disabled:false,innerHTML:id});
 const window={showToast:(message,type)=>toasts.push({message,type})};const document={addEventListener:(type,fn)=>events.push(type),getElementById:id=>buttons.get(id)||null,querySelectorAll:()=>[]};
 vm.runInNewContext(workerSource,{window,document,console,prompt:()=>reason,confirm:()=>true,fetch:async(url,options)=>{calls.push({url,options});if(fetcher)return fetcher(url,options);return response;},setInterval:()=>1,clearInterval(){},localStorage:{getItem:()=>null,setItem(){throw new Error('Failed action must not simulate saved state');}},Date,Set});return {window,events,calls,toasts,buttons};
}
test('worker module initializes and exposes every task control without ReferenceError',()=>{const h=worker();for(const name of ['rejectWorkerTask','workerAcceptTask','workerStartTravel','workerArrive','workerStartWork','workerPauseWork','workerResumeWork','workerCompleteWork','workerDelayTask'])assert.equal(typeof h.window[name],'function',name);assert.ok(h.events.includes('DOMContentLoaded'));});
test('reject requires a reason and cancellation sends no request',async()=>{for(const reason of [null,'  ']){const h=worker({reason});await h.window.rejectWorkerTask(42);assert.equal(h.calls.length,0);assert.equal(h.toasts.some(t=>t.type==='success'),false);}});
test('reject uses the existing audited reassignment endpoint and reports backend failure',async()=>{const h=worker({response:{ok:false,status:409,json:async()=>({message:'Assignment changed'})}});await h.window.rejectWorkerTask(42);assert.equal(h.calls[0].url,'/api/v1/auto-assignment/requests/42/reject');assert.equal(JSON.parse(h.calls[0].options.body).reason,'Parts unavailable');assert.equal(h.toasts[0].message,'Assignment changed');assert.equal(h.toasts.some(t=>t.type==='success'),false);});
test('attendance failures restore controls and never simulate a saved attendance state',async()=>{for(const action of ['workerClockIn','workerClockOut','workerStartBreak','workerEndBreak']){const h=worker({response:{ok:false,status:400,json:async()=>({message:'Attendance refused'})}});await h.window[action]();assert.equal(h.toasts[0].message,'Attendance refused');for(const button of h.buttons.values())assert.equal(button.disabled,false);assert.equal(h.toasts.some(t=>t.type==='success'||t.type==='info'),false);}});
test('attendance prevents concurrent duplicate actions',async()=>{let finish;const h=worker({fetcher:()=>new Promise(resolve=>finish=resolve)});const pending=h.window.workerClockIn();await h.window.workerClockIn();await h.window.workerStartBreak();assert.equal(h.calls.length,1);finish({ok:false,json:async()=>({message:'Try again'})});await pending;assert.equal(h.buttons.get('btnWorkerClockIn').disabled,false);});
const managerSource=fs.readFileSync('src/main/resources/static/smartapartment/js/maintenance-manager-dashboard.js','utf8');
test('live manager renders bind each manual action button only once',()=>{const start=managerSource.indexOf('    const boundActionButtons'),end=managerSource.indexOf('    // Audited Manual Action Handlers',start);const listeners=[];let called=0;const button={dataset:{act:'assign',id:'42'},addEventListener:(type,fn)=>listeners.push(fn)};vm.runInNewContext(managerSource.slice(start,end)+';attachActionListeners();attachActionListeners();',{WeakSet,document:{querySelectorAll:()=>[button]},handleManualAction:()=>called++});assert.equal(listeners.length,1);listeners[0]({preventDefault(){}});assert.equal(called,1);});
test('manager API failures are returned to the form instead of reporting success',async()=>{const start=managerSource.indexOf('    async function executeSimpleAction'),end=managerSource.indexOf('    function showManagerToast',start);const toasts=[];let refreshes=0;const scope={fetch:async()=>({ok:false,json:async()=>({message:'Worker is on leave'})}),showManagerToast:(...args)=>toasts.push(args),loadDashboardSummary:()=>refreshes++};vm.runInNewContext(managerSource.slice(start,end)+';this.run=executeSimpleAction;',scope);assert.equal(await scope.run('/action',{},'Saved'),false);assert.equal(toasts[0][1],'Worker is on leave');assert.equal(refreshes,0);});
test('shared interface leaves PropertyDirect completely unchanged',()=>{const source=fs.readFileSync('src/main/resources/static/smartapartment/js/dashboard-interface.js','utf8');vm.runInNewContext(source,{Set,document:{readyState:'complete',body:{dataset:{platform:'propertydirect',dashboardRole:'admin'}},querySelectorAll(){throw new Error('PropertyDirect must be excluded');}}});});
test('technician profile requires a name and never reports success when browser persistence fails',()=>{
 const template=fs.readFileSync('src/main/resources/templates/dashboards/maintenance.html','utf8');
 const start=template.indexOf("                const profileSaveBtn = e.target.closest('[data-action=\"save\"]');");
 const end=template.indexOf('                // Copy Worker Login Action',start);assert.ok(start>0&&end>start);
 for(const name of ['', 'Technician']) {
  const notices=[];let saves=0;const button={closest:()=>true};
  const document={getElementById:id=>({value:id==='techName'?name:'',focus(){}})};
  const scope={document,window:{showToast:(...args)=>notices.push(args)},localStorage:{setItem(){saves++;throw new Error('Storage unavailable');}},Date,setTimeout(){throw new Error('Failed saves must not schedule success UI');}};
  vm.runInNewContext('this.handle=function(e){'+template.slice(start,end)+'}',scope);
  scope.handle({target:{closest:()=>button},preventDefault(){},stopPropagation(){},stopImmediatePropagation(){}});
  assert.equal(saves,name?1:0);assert.equal(notices.length,1);assert.equal(notices[0][1],'danger');
 }
});
